baseURL = "/"

disqusShortname = ""
paginate = "6"
summaryLength = "15"
theme = "hugo-foundation-6-theme"
title = "Test Site"
[[menu.main]]
URL = "about"
name = "About Us"
weight = 1
[[menu.main]]
URL = "services"
name = "Service"
weight = 2
[[menu.main]]
URL = "portfolio"
name = "Portfolio"
weight = 3
[[menu.main]]
URL = "team"
name = "Team"
weight = 4
[[menu.main]]
URL = "pricing"
name = "Pricing"
weight = 5
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 6
[[menu.main]]
URL = "contact"
name = "Contact"
weight = 7
[params]
author = "codeblu"
description = "foundation skeleton for hugo"
google_analitycs_id = ""
logo = "images/logo.png"
post_share = true

[[params.plugins.css]]
link = "plugins/foundation/css/app.css"
[[params.plugins.css]]
link = "plugins/foundation-icons/foundation-icons.css"
[[params.plugins.css]]
link = "https://fonts.googleapis.com/css?family=Anaheim|Quattrocento+Sans:400,700&display=swap"

[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/foundation/js/app.js"
[[params.plugins.js]]
link = "plugins/what-input/what-input.js"
[[params.plugins.js]]
link = "plugins/lazy-load/lazy.js"

[[params.social]]
icon = "ti-facebook"
link = "#"
[[params.social]]
icon = "ti-twitter-alt"
link = "#"
[[params.social]]
icon = "ti-youtube"
link = "#"
[[params.social]]
icon = "ti-linkedin"
link = "#"
[[params.social]]
icon = "ti-dribbble"
link = "#"
[[params.social]]
icon = "ti-pinterest"
link = "#"
